Reset retry count on successful download
By adding it to removed-keys in dissoc-internal, we fix the
previous test. Also, it turned out that we had an off-by-one
error: if :retries is the maximum numbers of retries, then
< should be <=.